In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [8]:
b = np.array([[9.0,5,7.0], [6.0,2.0,4.0]])
print(b)

[[9. 5. 7.]
 [6. 2. 4.]]


In [11]:
# get dimension
print(a.ndim)
print(b.ndim)

1
2


In [14]:
# get shape
print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [20]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [23]:
print(a[1,5]) # get element
print(a[0, :]) # get a specific row
print(a[:, 2]) # get a specific column
print(a[0, 1:-1:2])

13
[1 2 3 4 5 6 7]
[ 3 10]
[2 4 6]


In [28]:
a[1,2] = 20
print(a)
a[:, 2] = [55, 44]
print(a)

[[ 1  2 55  4  5  6  7]
 [ 8  9 20 11 12 13 14]]
[[ 1  2 55  4  5  6  7]
 [ 8  9 44 11 12 13 14]]


In [29]:
# 3d

In [34]:
b = np.array([[[1,2],[3,4]], [[5,6], [7,8]]])
print(b)
print(b[0,1,1])

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
4


In [35]:
# all 0s matrix
np.zeros(2)

array([0., 0.])

In [37]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [38]:
np.zeros((2,2, 3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [39]:
# all 1s matrix
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [40]:
# any other numbers
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [41]:
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [43]:
# random decimal numbers
print(np.random.rand(4,2))
print(np.random.random_sample(a.shape))

[[0.14353964 0.93916061]
 [0.76960632 0.10011858]
 [0.72189735 0.41581139]
 [0.18492218 0.33036395]]
[[0.33197363 0.87457865 0.56192062 0.14548735 0.55096078 0.96208864
  0.47097978]
 [0.60402066 0.63235745 0.01019985 0.7122637  0.11252219 0.12756926
  0.03105201]]


In [47]:
# random integer values
np.random.randint(2, 8, size=(3,3))

array([[5, 2, 6],
       [5, 6, 3],
       [6, 2, 2]])

In [48]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [49]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [53]:
output = np.ones((5,5))

z = np.zeros((3,3))
z[1,1] = 9

output[1:4, 1:4] = z

print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [54]:
# be carful when u copying arrays!!

In [56]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a, b)

[1 2 3] [100   2   3]


### Mathematics

In [57]:
a = np.array([1,2,3])

In [58]:
a+2

array([3, 4, 5])

In [59]:
a*2

array([2, 4, 6])

In [60]:
a/2

array([0.5, 1. , 1.5])

In [61]:
a-2

array([-1,  0,  1])

In [62]:
a**2

array([1, 4, 9])

In [63]:
# sin of all values
np.sin(a)
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 ])

### Linaer Algebra

In [66]:
a = np.full((2,3), 1)
print(a)
b = np.full((3,2), 2)
print(b)

[[1 1 1]
 [1 1 1]]
[[2 2]
 [2 2]
 [2 2]]


In [67]:
np.matmul(a, b)

array([[6, 6],
       [6, 6]])

In [68]:
c = np.identity(3)
np.linalg.det(c)

1.0

### Statistics

In [73]:
stats = np.array([[1,2,3], [4,5,6]])
print(np.min(stats))
print(np.max(stats))
print(np.sum(stats))

1
6
21


### Reorganizing Arrays

In [77]:
before = np.array([[1,2,3,4], [5,6,7,8]])
print(before)

after = before.reshape((4, 2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [79]:
# vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [81]:
#horizontal stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1, h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])